language: node_js
node_js:
  - "0.6"
  - "0.8"
  - "0.10"
  - "0.12"
  - "1.0"
  - "1.8"
  - "2.0"
  - "2.4"
  - "3.0"
  - "3.3"
  - "4.0"
  - "4.2"
  - "5.0"
  - "5.5"
sudo: false
script: "npm test"
