language: node_js
node_js:
  - "0.6"
  - "0.8"
  - "0.10"
  - "0.12"
  - "1.8"
  - "2.4"
  - "3.3"
  - "4.8"
  - "5.12"
  - "6.10"
  - "7.7"
sudo: false
cache:
  directories:
    - node_modules
before_install:
  # Setup Node.js version-specific dependencies
  - "test $TRAVIS_NODE_VERSION != '0.6' || npm rm --save-dev nyc"
  - "test $TRAVIS_NODE_VERSION != '0.8' || npm rm --save-dev nyc"
  # Update Node.js modules
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
script:
  # Run test script, depending on nyc install
  - "test ! -z $(npm -ps ls nyc) || npm test"
  - "test   -z $(npm -ps ls nyc) || npm run-script test-ci"
